### ISSUE TITLE
Silent error when setting a waveform to constant 0

### ISSUE THREAD

**Issue by maarten-ic** [iterorganization/Waveform-Editor#54]
Reproduction: load the following YAML configuration:

```yaml
globals:
  dd_version: 4.0.0
test
  test/waveform: 0
```

This triggers an error: Cannot have an empty waveform, but this error is not visible anywhere (GUI or CLI).
Offending code: https://github.com/iterorganization/Waveform-Editor/blob/develop/waveform_editor/yaml_parser.py#L185

To fix:
1. Ensure that errors raised during YAML parsing are visible to the user in GUI / CLI
2. Allow having a waveform with constant 0 value
